version: "3.8"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "order"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"